## we must upload ocf scripts on all controllers before
## start pacemaker and create clone resources.
- id: primary_create_redis_ocf
  type: puppet
  groups: [primary-controller]
  required_for: [primary-cluster]
  requires: [fuel_pkgs]
  parameters:
    puppet_manifest: "puppet/manifests/create_redis_ocf.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 180

- id: create_redis_ocf
  type: puppet
  groups: [controller]
  required_for: [cluster]
  requires: [fuel_pkgs]
  cross-depends:
    - name: primary_create_redis_ocf
  parameters:
    puppet_manifest: "puppet/manifests/create_redis_ocf.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 180

- id: primary_ceilometer_redis
  type: puppet
  groups: [primary-controller]
  required_for: [deploy_end]
  requires: [ceilometer-controller]
  cross-depends:
    - name: create_redis_ocf
  parameters:
    puppet_manifest: "puppet/manifests/controller.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 3600

- id: ceilometer_redis
  type: puppet
  groups: [controller]
  required_for: [deploy_end]
  requires: [ceilometer-controller]
  cross-depends:
    - name: primary_ceilometer_redis
  parameters:
    puppet_manifest: "puppet/manifests/controller.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 3600
